# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  wip:
    runs-on: ubuntu-latest
    steps:
      - name: WIP
        uses: wip/action@v1.1.0
